version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - data
      - client
  server:
    image: amazoncorretto:21
    container_name: server
    ports:
      - "8080:8080"
    working_dir: /server
    volumes:
      - ./server:/server
    command: sh -c "chmod +x run.sh && sh run.sh"
  data:
    image: python:latest
    container_name: data
    ports:
      - "8000:8000"
    working_dir: /data
    volumes:
      - ./data:/data
    command: sh -c "chmod +x run.sh && sh run.sh"
  client:
    image: node:latest
    container_name: client
    ports:
      - "3000:3000"
    working_dir: /client
    volumes:
      - ./client:/client
    command: sh -c "chmod +x run.sh && sh run.sh"
